pwrData <- read.table("household_power_consumption.txt", header = TRUE, sep = ";", na.strings = "?")
pwrData$Date <- as.Date(pwrData$Date, "%d/%m/%Y")
pwrData2 <- subset(pwrData, pwrData$Date == "2007-02-01" | pwrData$Date == "2007-02-02")
pwrData2$Global_active_power <- as.numeric(pwrData2$Global_active_power)
pwrData2$dateTime <- strptime(paste(pwrData2$Date, pwrData2$Time), "%Y-%m-%d %H:%M:%S")
par(mfrow=c(2,2))
with(pwrData2, plot(dateTime, Global_active_power, type = "l", xlab = "", ylab = "Global Active Power (kilowatts)"))
with(pwrData2, plot(pwrData2$dateTime, Voltage, type = "l", xlab = "datetime", ylab = "Voltage"))
plot(pwrData2$dateTime, pwrData2$Sub_metering_1 ,xlab = "",ylab= "Energy sub metering", type = "n")
lines(pwrData2$dateTime, pwrData2$Sub_metering_1)
lines(pwrData2$dateTime, pwrData2$Sub_metering_2, col = "red")
lines(pwrData2$dateTime, pwrData2$Sub_metering_3, col = "blue")
legend("topright", lty = c(1,1,1),bty = "n" ,legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col = c("black","red","blue"))
with(pwrData2, plot(dateTime, Global_reactive_power, type = "l", xlab = "datetime"))
dev.copy(png, file="plot4.png", width = 480, height = 480)
dev.off()