pwrData <- read.table("household_power_consumption.txt", header = TRUE, sep = ";", na.strings = "?")
pwrData$Date <- as.Date(pwrData$Date, "%d/%m/%Y")
pwrData2 <- subset(pwrData, pwrData$Date == "2007-02-01" | pwrData$Date == "2007-02-02")
pwrData2$Global_active_power <- as.numeric(pwrData2$Global_active_power)
pwrData2$dateTime <- strptime(paste(pwrData2$Date, pwrData2$Time), "%Y-%m-%d %H:%M:%S")
plot(pwrData2$dateTime, pwrData2$Sub_metering_1 ,xlab = "",ylab= "Energy sub metering", type = "n")
lines(pwrData2$dateTime, pwrData2$Sub_metering_1)
lines(pwrData2$dateTime, pwrData2$Sub_metering_2, col = "red")
lines(pwrData2$dateTime, pwrData2$Sub_metering_3, col = "blue")
legend("topright", lty = c(1,1,1), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col = c("black","red","blue"))
dev.copy(png, file="plot3.png", width = 480, height = 480)
dev.off()